title: "&nbsp;&nbsp;&nbsp;" # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <strong>Background</strong><br>
  ðŸ“Š <a href="#project_1">Project 1</a><br>
  ðŸ’¼ <a href="#project_2">Project 2</a><br><br>

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme
