title: Lorenzo Racadio
logo: /assets/img/headshot_circle.png
description: |
  ğŸ“ <strong>+1 (312) 735-3411</strong><br>
  âœ‰ï¸ <a href="mailto:lorenzo.racadio@gmail.com">lorenzo.racadio@gmail.com</a><br>
  ğŸ”— <a href="https://linkedin.com/in/renzo-racadio-rrn" target="_blank">linkedin.com/in/renzo-racadio-rrn</a>
show_downloads: false
theme: jekyll-theme-minimal
