title: Lorenzo Racadio
logo: /assets/img/headshot_circle.png
description: |
  <img src="/assets/img/headshot_circle.png" alt="Headshot" style="width:150px; border-radius:50%;"><br>
  ğŸ“ <b>+13127353411</b><br>
  âœ‰ï¸ <a href="mailto:lorenzo.racadio@gmail.com">lorenzo.racadio@gmail.com</a><br>
  ğŸ”— <a href="https://linkedin.com/in/renzo-racadio-rrn" target="_blank">linkedin.com/in/renzo-racadio-rrn</a><br>
  ğŸ“š <a href="#education">Education</a><br>
  ğŸ’¼ <a href="#work-history">Work History</a><br>
  ğŸ§  <a href="#professional-projects">Professional Projects</a><br>
  ğŸ› ï¸ <a href="#personal-projects">Personal Projects</a><br>

# Theme
theme: jekyll-theme-minimal

# Sections
show_downloads: false
