title: Lorenzo Racadio
logo: /assets/img/headshot_circle.png
description: |
  ğŸ“ +1 (312) 735-3411 |
  âœ‰ï¸ lorenzo.racadio@gmail.com |  
  ğŸ”— linkedin.com/in/renzo-racadio-rrn |
show_downloads: false
theme: jekyll-theme-minimal
